name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: git config
        run: git config user.name "Lisenapati"
        run: git config user.email "lisenhatson@gmail.com"

      - name: Build and deploy
        run: npm run deploy
